
#ifndef NAV2_SMAC_PLANNER_COMMON_EXPORT_H
#define NAV2_SMAC_PLANNER_COMMON_EXPORT_H

#ifdef NAV2_SMAC_PLANNER_COMMON_STATIC_DEFINE
#  define NAV2_SMAC_PLANNER_COMMON_EXPORT
#  define NAV2_SMAC_PLANNER_COMMON_NO_EXPORT
#else
#  ifndef NAV2_SMAC_PLANNER_COMMON_EXPORT
#    ifdef nav2_smac_planner_common_EXPORTS
        /* We are building this library */
#      define NAV2_SMAC_PLANNER_COMMON_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define NAV2_SMAC_PLANNER_COMMON_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef NAV2_SMAC_PLANNER_COMMON_NO_EXPORT
#    define NAV2_SMAC_PLANNER_COMMON_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef NAV2_SMAC_PLANNER_COMMON_DEPRECATED
#  define NAV2_SMAC_PLANNER_COMMON_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef NAV2_SMAC_PLANNER_COMMON_DEPRECATED_EXPORT
#  define NAV2_SMAC_PLANNER_COMMON_DEPRECATED_EXPORT NAV2_SMAC_PLANNER_COMMON_EXPORT NAV2_SMAC_PLANNER_COMMON_DEPRECATED
#endif

#ifndef NAV2_SMAC_PLANNER_COMMON_DEPRECATED_NO_EXPORT
#  define NAV2_SMAC_PLANNER_COMMON_DEPRECATED_NO_EXPORT NAV2_SMAC_PLANNER_COMMON_NO_EXPORT NAV2_SMAC_PLANNER_COMMON_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef NAV2_SMAC_PLANNER_COMMON_NO_DEPRECATED
#    define NAV2_SMAC_PLANNER_COMMON_NO_DEPRECATED
#  endif
#endif

#endif /* NAV2_SMAC_PLANNER_COMMON_EXPORT_H */
