controller_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: false
    controller_frequency: 20.0

    progress_checker_plugins:
      - progress_checker
    goal_checker_plugins:
      - goal_checker
    controller_plugins:
      - FollowPath

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 15.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: false

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      motion_model: "Ackermann"
      time_steps: 50
      model_dt: 0.05
      batch_size: 2000
      iteration_count: 1
      temperature: 0.3
      gamma: 0.015

      vx_max: 1.0
      vx_min: -0.4
      wz_max: 1.5
      wz_limit: 1.5
      ax_max: 2.0
      ay_max: 0.0
      vy_max: 0.0

      vx_std: 0.4
      vy_std: 0.0
      wz_std: 0.3

      lookahead_dist: 1.0
      transform_tolerance: 0.3
      debug_trajectory: false
      visualize: true
      publish_optimal_trajectory: true
      publish_critics_stats: false
      prune_distance: 3.0
      max_robot_pose_search_dist: 3.0
      retry_attempt_limit: 1
      regenerate_noises: true

      enforce_path_inversion: true
      inversion_xy_tolerance: 0.25
      inversion_yaw_tolerance: 0.4

      path_cost_weight: 10.0
      goal_cost_weight: 15.0
      smooth_cost_weight: 0.2
      obstacle_cost_weight: 15.0
      rotate_cost_weight: 30.0
      prefer_forward_penalty: 0.5

      critics:
        - PathFollowCritic
        - PathAngleCritic
        - PathAlignCritic
        - GoalCritic
        - GoalAngleCritic
        - CostCritic   # 🆕 nouveau critic ajouté

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        offset_from_furthest: 6
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5
        threshold_to_consider: 0.5
        offset_from_furthest: 4
        max_angle_to_furthest: 1.0
        mode: 2

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        threshold_to_consider: 0.5
        offset_from_furthest: 14
        trajectory_point_step: 3
        use_path_orientations: true

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        threshold_to_consider: 1.5

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.8

      # === 🆕 CostCritic : favorise les zones à faible coût sur la costmap ===
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0          # poids du coût relatif au reste
        critical_cost: 254.0         # valeur de coût max considérée comme obstacle
        consider_footprint: true   # prend en compte le footprint complet
        inflation_cost_scaling: 0.5 # adoucit la pénalisation autour des obstacles

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: robot1/odom
      robot_base_frame: robot1/base_footprint

      rolling_window: true
      width: 20
      height: 20
      resolution: 0.05
      update_frequency: 10.0
      publish_frequency: 10.0

      footprint: "[ [0.25, 0.42], [0.25, -0.42], [-1.05, -0.42], [-1.05, 0.42] ]"
      footprint_padding: 0.02

      plugins:
        - gridmap_fusion_layer
        - inflation_layer

      gridmap_fusion_layer:
        plugin: "hive_costmap/GridmapFusionLayer"
        enabled: true
        # Topic OccupancyGrid publié par ton simple_costmap_node
        og_topic: "/hive_costmap/grid_occupancy"   # <-- ajuste si ton topic est différent (ex: /real_obstacle_occupancy)
        clear_footprint: true                      # nettoie le footprint dans la master grid

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 2.0
        inflation_radius: 0.35

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: robot1/odom
      robot_base_frame: robot1/base_footprint

      rolling_window: true
      width: 40
      height: 40
      resolution: 0.05
      update_frequency: 5.0
      publish_frequency: 2.0

      footprint: "[ [0.25, 0.40], [0.25, -0.40], [-0.90, -0.40], [-0.90, 0.40] ]"
      footprint_padding: 0.02

      plugins:
        - gridmap_fusion_layer
        - inflation_layer

      gridmap_fusion_layer:
        plugin: "hive_costmap/GridmapFusionLayer"
        enabled: true
        og_topic: "/hive_costmap/grid_occupancy"   # même source ou une autre si tu veux
        clear_footprint: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 2.0
        inflation_radius: 0.35

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 2.0
    planner_plugins:
      - SmacPlannerHybrid

    SmacPlannerHybrid:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      tolerance: 0.5
      allow_unknown: true
      downsample_costmap: false
      motion_model_for_search: "REEDS_SHEPP"
      angle_quantization_bins: 72
      minimum_turning_radius: 1.0
      reverse_penalty: 2.0
      cost_travel_multiplier: 2.0
      cost_heuristic_multiplier: 0.8
      analytic_expansion_ratio: 3.5
      cache_obstacle_heuristic: true
      lookup_table_size: 20.0
      allow_reverse_expansion: true
      smooth_path: true
      smooth_path_max_cost_factor: 2.0
